name: Ubuntu Latest Build

on:
  push:
    branches: [ 'development' ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        working-directory: build
        run: |
          ./build.sh

      - name: Verify build artifacts
        working-directory: build
        run: |
          echo "###  Verifying deb package  ###"
          ls -al *.deb
          ehco "######################################"
          echo "###  Verifying rpm package  ###"
          ls -al *.rpm
          echo "######################################"
          echo "###  Verifying tar.gz package  ###"
          ls -al *.tar.gz
          echo "######################################"