name: Matrix Builds

on:
  push:
    branches: [ 'developmen-v4' ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # os: [ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-22.04-arm]
        # os: [macos-13, macos-15-intel, macos-14, macos-15, macos-26]
        os: [macos-13]


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check python version
        run: |
          echo "Checking Python version on ${{ matrix.os }}"
          python --version

      - name: Build on Linux/macOS
        working-directory: build
        if: runner.os != 'Windows'
        run: |
          # echo "Running standard build script for Linux/macOS"
          sudo ./build.sh

      - name: Build on Windows
        working-directory: build
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Running Windows-specific build script"
          build_windows.bat

      - name: Verify build artifacts
        working-directory: build
        if: runner.os != 'Windows'
        run: |
          echo "###  Verifying deb package  ###"
          ls -al