name: Matrix Builds

on:
  push:
    branches: [ 'development-v2' ]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        working-directory: build
        run: |
          ./build.sh
