name: Ubuntu Latest Build

on:
  push:
    branches: [ 'development' ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        working-directory: build
        run: |
          ./build.sh

      - name: Verify build artifacts
        working-directory: build
        run: |
          ls -al