name: CentOS 9 Build

on:
  push:
    branches: [ 'development' ]

jobs:
  build-and-test:
    runs-on: self-hosted # This targets your CentOS 9 self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project (example)
        run: |
          ./build/build.sh
