name: Ubuntu Latest Build

on:
  push:
    branches: [ 'development' ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        working-directory: build
        run: |
          ./build.sh

      - name: Verify build artifacts
        working-directory: build
        run: |
          echo "###  Verifying deb package  ###"
          ls -al *.deb
          echo "######################################"
          echo "###  Verifying rpm package  ###"
          ls -al *.rpm
          echo "######################################"
          echo "###  Verifying tar.gz package  ###"
          ls -al *.tar.gz
          echo "######################################"

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: ncparpm-release
          path: build/*.rpm

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: ncpa-deb-release
          path: build/*.rpm

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: ncpa-tarball-release
          path: build/*.tar.gz